\
                /* This file was generated by blade */
                extern "C" {
                namespace binary_version {
                extern const int kSvnInfoCount = 1;
                extern const char* const kSvnInfo[] = {"git@github.com:Basket-of-Charcoal/MachineLearning.git@c68e59aa63a52f977cb015fdf7d16679c92ece24\n"};
                extern const int kScmInfoCount = 1;
                extern const char* const kScmInfo[] = {"git@github.com:Basket-of-Charcoal/MachineLearning.git@c68e59aa63a52f977cb015fdf7d16679c92ece24\n"};
                extern const char kBuildType[] = "debug";
                extern const char kBuildTime[] = "Wed Oct 28 12:55:05 2020";
                extern const char kBuilderName[] = "bytedance";
                extern const char kHostName[] = "C02D316LMD6R";
                extern const char kCompiler[] = "gcc 12.0.0";
                }}